export const TEMPLATES_DATA = [
    // {
    //     id: "modern-executive",
    //     categoryId: "technology",
    //     badgeText: "Premium",
    //     badgeTheme: "premium",
    //     categoryText: "Công nghệ (IT)",
    //     title: "Modern Executive",
    //     subtitle: "Kiến trúc sư giải pháp & IT",
    //     style: "Executive",
    //     type: "Popular",
    //     image: "https://i.postimg.cc/W4gN1DNg/minimal.png",
    //     rating: 4.9,
    //     downloads: 2500,
    //     description: "Mẫu thiết kế dành cho các lãnh đạo cấp cao trong ngành IT, nhấn mạnh vào thành tựu chiến lược và quản lý đội ngũ kỹ thuật.",
    //     features: ["Chuẩn ATS 100%", "Tối ưu cho CTO/Engineering Manager", "Thiết kế sang trọng", "Điểm nhấn thành tựu"]
    // // },
    // {
    //     id: "creative-minimalist",
    //     categoryId: "technology",
    //     badgeText: "Free",
    //     badgeTheme: "free",
    //     categoryText: "Công nghệ (IT)",
    //     title: "Creative Minimalist",
    //     subtitle: "Frontend Developer / UI Designer",
    //     style: "Minimalist",
    //     type: "Newest",
    //     image: "https://i.postimg.cc/tJTGW7jP/modern.png",
    //     rating: 4.7,
    //     downloads: 1800,
    //     description: "Sự kết hợp hoàn hảo giữa tinh tế và hiện đại, phù hợp cho các lập trình viên Frontend và Designer.",
    //     features: ["Layout thoáng", "Tông màu trung tính", "Tập trung vào Portfolio", "Dễ dàng tùy chỉnh"]
    // },
    {
        id: "the-standard",
        categoryId: "technology",
        badgeText: "Pro",
        badgeTheme: "pro",
        categoryText: "Công nghệ (IT)",
        title: "The Standard",
        subtitle: "Backend Engineer / System Admin",
        style: "Modern",
        type: "Popular",
        image: "https://i.postimg.cc/g25jJFvk/vintage.png",
        rating: 4.8,
        downloads: 3100,
        description: "Mẫu CV chuẩn mực, chuyên nghiệp, phù hợp cho mọi vị trí kỹ thuật đòi hỏi sự nghiêm túc và chính xác.",
        features: ["Cấu trúc rõ ràng", "Phông chữ chuyên nghiệp", "Tối ưu cho nhà tuyển dụng", "Chuẩn ATS"]
    },
    {
        id: "data-scientist",
        categoryId: "technology",
        badgeText: "Premium",
        badgeTheme: "premium",
        categoryText: "Công nghệ (IT)",
        title: "Data Scientist",
        subtitle: "Kỹ sư Dữ liệu / AI",
        style: "Modern",
        type: "Newest",
        image: "https://i.postimg.cc/zX4YHJPg/classic.png",
        rating: 4.9,
        downloads: 1200,
        description: "Thiết kế đặc thù cho dân Tech, tối ưu hóa việc hiển thị các kỹ năng lập trình, mô hình AI và dự án thực tế.",
        features: ["Ma trận kỹ năng", "Highlight dự án", "Tối ưu từ khóa AI", "Layout hiện đại"]
    },
    {
        id: "portfolio-hybrid",
        categoryId: "technology",
        badgeText: "Free",
        badgeTheme: "free",
        categoryText: "Công nghệ (IT)",
        title: "Portfolio Hybrid",
        subtitle: "Fullstack Developer / UI/UX",
        style: "Creative",
        type: "Popular",
        image: "https://i.postimg.cc/GtchNc1m/polished.png",
        rating: 4.6,
        downloads: 4200,
        description: "Mẫu lai giữa CV truyền thống và Portfolio, giúp bạn phô diễn các project code và giao diện một cách ấn tượng.",
        features: ["Tích hợp link Github/Behance", "Màu sắc năng động", "Bố cục linh hoạt", "Thu hút thị giác"]
    },
    {
        id: "boardroom-ready",
        categoryId: "technology",
        badgeText: "Pro",
        badgeTheme: "pro",
        categoryText: "Công nghệ (IT)",
        title: "Boardroom Ready",
        subtitle: "IT Director / Product Head",
        style: "Executive",
        type: "Popular",
        image: "https://i.postimg.cc/j2VyJnN9/formal.png",
        rating: 4.8,
        downloads: 900,
        description: "Vượt xa một bản CV, đây là một bản tuyên ngôn về năng lực quản trị công nghệ và tầm nhìn chiến lược.",
        features: ["Phong cách quyền lực", "Tập trung vào KPIs & Roadmap", "Chuẩn ATS cao cấp", "Thiết kế tối giản"]
    },
    {
        id: "cloud-expert",
        categoryId: "technology",
        badgeText: "Free",
        badgeTheme: "free",
        categoryText: "Công nghệ (IT)",
        title: "Cloud Specialist",
        subtitle: "DevOps / Cloud Architect",
        style: "Modern",
        type: "Newest",
        image: "https://i.postimg.cc/tJTGW7jP/modern.png",
        rating: 4.7,
        downloads: 1100,
        description: "Thiết kế sạch sẽ, tin cậy, tập trung vào các chứng chỉ AWS/Azure/GCP và hạ tầng hệ thống.",
        features: ["Nhấn mạnh chứng chỉ", "Cấu trúc khoa học", "Tối ưu cho Cloud roles", "Chuẩn ATS"]
    },
    {
        id: "security-analyst",
        categoryId: "technology",
        badgeText: "Pro",
        badgeTheme: "pro",
        categoryText: "Công nghệ (IT)",
        title: "Security Analyst",
        subtitle: "Cybersecurity Expert",
        style: "Minimalist",
        type: "Popular",
        image: "https://i.postimg.cc/W4gN1DNg/minimal.png",
        rating: 4.5,
        downloads: 1500,
        description: "Phù hợp cho các chuyên gia bảo mật, nhấn mạnh vào kỹ năng pentest, audit và quản lý rủi ro.",
        features: ["Bố cục chặt chẽ", "Trình bày kỹ thuật rõ ràng", "Chuẩn ATS", "Phong cách tin cậy"]
    }
];

export const TEMPLATE_CATEGORIES = [
    { id: 'all', label: 'Tất cả' },
    { id: 'technology', label: 'Công nghệ (IT)' },
];

export const TEMPLATE_STYLES = [
    'Minimalist',
    'Creative',
    'Executive',
    'Modern',
];
